builds:
  - skip: true

release:
  header: |
    wdb-go v{{ .Tag }} : Go Client Library for wunderDB
  footer: |
    **Full Changelog**: https://github.com/TanmoySG/wdb-go/compare/{{ .PreviousTag }}...{{ .Tag }}
  github:
    owner: TanmoySG
    name: wdb-go
  disable: false
  draft: true
  target_commitish: '{{ .Commit }}'